const PATHS = {
    MAIN: '/',
    LOGIN: '/member/login',
    JOIN_AGREEMENT: '/member/join-agreement',
    JOIN: '/member/join',
    JOIN_COMPLETED: '/member/join-completed',
    FIND_ID: '/member/find-id',
    FIND_PASSWORD: '/member/find-password',
    MY_PAGE: '/mypage',
    MY_INFO: '/mypage/info',
    MY_ORDER_LIST: '/mypage/order/list',
    MY_ORDER_DETAIL: '/mypage/order/detail',
    MY_PRODUCTS: '/mypage/products',
    MY_COUPONS: '/mypage/coupons',
    MY_ACCUMULATION: '/mypage/accumulation',
    MY_ROUND_ANALYSIS: '/mypage/round-analysis',
    MY_ROUND_ANALYSIS_MAIN: '/mypage/round-analysis/main',
    MY_ROUND_ANALYSIS_ROUND: '/mypage/round-analysis/round',
    MY_ROUND_ANALYSIS_STATISTICS: '/mypage/round-analysis/statistics',
    MY_PASSWORD: '/mypage/password',
    WITHDRAWAL: '/mypage/withdrawal',
    PRODUCT_LIST: '/product',
    PRODUCT_DETAIL: '/product/detail',
    CART: '/cart',
    SEARCH: '/search',
    EVENT_LIST: '/event/list',
    EVENT_DETAIL: '/event/detail',
    GUEST_LOGIN: '/guest/login',
    GUEST_ORDER: '/guest/order',
    GUEST_ORDER_DETAIL: '/guest/order-detail',
    ORDER: '/order/sheet',
    ORDER_AGREE: '/order/agreement',
    MANAGER: '/manager',
    MANUAL_LIST: '/manual/list',
    MANUAL_DETAIL: '/manual/detail',
    GOLF_COURSE_LIST: '/golf-course/list',
    GOLF_COURSE_DETAIL: '/golf-course/detail',
    GOLF_COURSE_REQUEST: '/golf-course/request',
    MY_INQUIRY: '/support/my-inquiry',
    INQUIRY: '/support/inquiry',
    SERVICE_CENTER: '/support/service-center',
    FAQ: '/etc/faq',
    NOTICE: '/etc/notice',
    NOT_FOUND: '/not-found',
    ERROR: '/error-server',
};

export default PATHS;
